### ISSUE TITLE
Improvement: In the Server-side > On-device decisioning pages combine language code boxes

### ISSUE THREAD

**Issue by judy-kim** [AdobeDocs/target-developers#111]
Issue in /src/pages/implement/server-side/sdk-guides/on-device-decisioning/execute-ab-tests-with-feature-flags.md

In the Server-side > On-device decisioning pages, there are several instances in which code for Node.js and Java are provided in separate code boxes. Combine into a single codebox with tabs.

**Comment by mtalbotgmail** [comment]
Fixed in new site.
