### ISSUE TITLE
Links to other pages within the dev site do not expand side nav as expected

### ISSUE THREAD

**Issue by judy-kim** [AdobeDocs/target-developers#112]
Issue in /src/pages/before-implement/implement-cname-support-in-target.md

"For more information about ITP, see [Apple Intelligent Tracking Prevention (ITP) 2.x](https://developer-stage.adobe.com/target/before-implement/privacy/apple-itp-2x/)."-- This link goes to another page within the dev doc portal, meaning it reloads in the current page as expected. However, the side nav fails to expand to indicate where in the site the user has been taken to. This loss of context is very confusing for users.

First noted in Issue #74.

**Comment by judy-kim** [comment]
Asked for assistance from IO team

**Comment by mtalbotgmail** [comment]
Not an issue in new site.
