### ISSUE TITLE
Add links back to BP guide

### ISSUE THREAD

**Issue by judy-kim** [AdobeDocs/target-developers#118]
Issue in /src/pages/implement/recommendations/index.md

Add note and link back to Business Practitioner guide - quick note at the top of the page (or end of page, or on the side). Specifically for this Recs topic, because it is the one isolated case where it's just the Recs Implementation piece that was moved out of the rest of the Recs stuff.

**Comment by mtalbotgmail** [comment]
Fixed in new guide.
