### ISSUE TITLE
Inconsistent cookie storage duration description

### ISSUE THREAD

**Issue by morritza** [AdobeDocs/target-developers#119]
Issue in /src/pages/before-implement/privacy/cookie-behavior.md

There are two cookie storage duration documented, which one is valid? I guess the two years are coming from the default configuration and the 2 weeks are from the recent browser privacy changes(ITP..).

mbox duration: "The cookie remains on the visitor’s browser two years from their last login. You cannot change the cookie duration."
https://experienceleague.adobe.com/docs/core-services/interface/administration/ec-cookies/cookies-target.html?lang=en

Cookie duration: "The cookie remains on the visitor's browser two weeks from the last login. You cannot change the cookie duration."
https://developer.adobe.com/target/before-implement/privacy/cookie-behavior/?lang=en#cookie-settings

By using targetGlobalSettings.deviceIdLifetime you can change the duration:
https://developer.adobe.com/target/implement/client-side/atjs/atjs-functions/targetglobalsettings/?lang=en#deviceidlifetime

**Comment by mtalbotgmail** [comment]
Thanks for your comment. The correct answer is two years and has been updated accordingly.
