### ISSUE TITLE
Typos in Node.js configuration parameter names

### ISSUE THREAD

**Issue by JPelka** [AdobeDocs/target-developers#124]
Issue in /src/pages/implement/server-side/node-js/initialize-sdk.md

I have identified two typos: 
`Client` instead of `client`
`organizationID` instead of `organizationId`.

Both params are required and error messages for both are a bit confusing, as they don't contain the exact expected parameter name, but a misleading, prettyfied version:

`Error: Client is required` may suggest an upper-case spelling as well.
`Error: Organization Id is required` is not super-specific as well, but at least the lowercase 'd' hints at the problem.

**Comment by judy-kim** [comment]
Resolved
