### ISSUE TITLE
the call to Target Rest api with JSON array object is throwing errors

### ISSUE THREAD

**Issue by aashlesh** [AdobeDocs/target-developers#126]
we are passing custom parameters via data-provider integration and the internal call happens to this URL: 
`https://<client>.tt.omtrdc.net/rest/v1/delivery?client=<client>&sessionId=1d83b1d9f8614ac4842aa72eacd13f87&version=2.9.0`

the parameters we pass is a JSON Array and it looks something like below. However it throws error `Invalid Json. Location: line - 35, column - 36` thought the below requested JSON is valid.

Is passing JSON Array Supported?  

Error is thrown at this part in the below request: 
```
               [
                    "ABC",
                    "XYZ"
                ]
```

```
{
    "requestId": "b0195390d93c465ab6fad307f5d7ae0e",
    "context": {
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0",
        "timeOffsetInMinutes": -420,
        "channel": "web",
        "screen": {
            "width": 1728,
            "height": 1117,
            "orientation": "landscape",
            "colorDepth": 30,
            "pixelRatio": 2
        },
        "window": {
            "width": 1728,
            "height": 346
        },
        "browser": {
            "host": "broman",
            "webGLRenderer": "Apple M1"
        },
        "address": {
            "url": "http://test/test.html",
            "referringUrl": ""
        }
    },
    "experienceCloud": {
        "analytics": {
            "logging": "server_side"
        }
    },
    "execute": {
        "pageLoad": {
            "parameters": {                
                "estore_com_ents": [
                    "ABC",
                    "XYZ"
                ]
            }
        }
    }
}
```

**Comment by judy-kim** [comment]
Hi Aashlesh, we do not support arrays in the parameters object. The properties of the parameters object must be of type _string_. I have logged internal ticket TNT-46273 to clarify this in the Delivery API documentation at https://developer.adobe.com/target/implement/delivery-api/#operation/execute. Thank you for raising this issue.

**Comment by dplacinta** [comment]
Updated documentation and example with #203
