### ISSUE TITLE
Link to the new Documentation

### ISSUE THREAD

**Issue by SydneeChristensen** [AdobeDocs/target-developers#215]
Issue in /src/pages/implement/mobile/index.md

The link to the v5 mobile docs is to mobile documentation that is out of date that then links them to the new docs, can we update the link on this page to go straight to the new documentation? Here is that new link: https://developer.adobe.com/client-sdks/documentation/

**Comment by mtalbotgmail** [comment]
Changed link. Thanks, Sydnee. You might need to refresh browser or clear cache.
