### ISSUE TITLE
v4 mobile sdk

### ISSUE THREAD

**Issue by SydneeChristensen** [AdobeDocs/target-developers#216]
Issue in /src/pages/implement/mobile/index.md

The v4 mobile SDK is no longer supported, I think we should make that clear on this page. 
Something like: 
Support for the Mobile [version 4 SDKs](https://github.com/Adobe-Marketing-Cloud/mobile-services) has ended as of August 31, 2021 and is no longer recommended for Adobe Target mobile users, but If you are leveraging the SDK 4.x, the mobile app targeting process includes the following steps: ....

And then I am assuming that the things listed under v4 do not apply to later SDKs, so I think if we create a heading on the left nav bar called something like "version 4 mobile SDK" and then put
[How Target works in mobile apps](https://developer.adobe.com/target/implement/mobile/how-target-works-mobile-apps/)
[Enable Target in the SDK](https://developer.adobe.com/target/implement/mobile/enable-target-in-sdk/)
[Create a Target location and success metric](https://developer.adobe.com/target/implement/mobile/mobile-create-location-and-metric/)
[Send custom user data](https://developer.adobe.com/target/implement/mobile/mobile-custom-user-data/) 
all under that header.

**Comment by mtalbotgmail** [comment]
Fixed in the new site, which will go live soon. Thanks.
https://experienceleague.corp.adobe.com/docs/target-dev/developer/mobile-apps/overview.html?lang=en
