### ISSUE TITLE
Intermittent latency when downloading business rfi forms

### ISSUE THREAD

**Issue by sgoffadobe** [AdobeDocs/target-developers#22]
Issue in /src/pages/before-implement/prepare-to-implement-target.md

Steps to reproduce:
1. Go to URL https://developer-stage.adobe.com/target/before-implement/prepare-to-implement-target/#adobe-target-business-request-for-information
2. Click either "Download the [Business Request for Information](https://developer-stage.adobe.com/target/business-rfi.docx) document" or "Download the [Technical Request for Information](https://developer-stage.adobe.com/target/business-rfi.docx) document"

Current Behavior: Sometimes the link does not work or the download happens very slowly. Sometimes it works fine.
Expected Behavior: Forms download in a timely manner at all times.

**Comment by judy-kim** [comment]
Can not reproduce: When I go to the source URL https://developer-stage.adobe.com/target/before-implement/prepare-to-implement-target/ and click either the "Download the Business RFI" or "Download the Technical RFI" doc, I'm able to download both docs without observing latency. Tried a few times on different days, at different times of the day.
