### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mmaxen** [AdobeDocs/target-developers#28]
Issue in /src/pages/implement/client-side/atjs/on-device-decisioning/on-device-decisioning.md

These 2 links pointed out in the screenshot are not loading

![image](https://user-images.githubusercontent.com/106278998/170361861-4d51d520-e675-4839-880f-4a27cbfb47ab.png)

**Comment by judy-kim** [comment]
Links working now, likely as a result of resolving Issue #78
