### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mmaxen** [AdobeDocs/target-developers#32]
Issue in /src/pages/implement/client-side/atjs/on-device-decisioning/on-device-decisioning.md

This link seen in the screenshot is broken

![image](https://user-images.githubusercontent.com/106278998/170362424-a3d37c0b-7d68-4e8d-a6b5-7b81291f0812.png)

**Comment by judy-kim** [comment]
Fixed when resolved Issue #78
