### ISSUE TITLE
Yellow highlighted "#" next to every title

### ISSUE THREAD

**Issue by sgoffadobe** [AdobeDocs/target-developers#34]
Issue in /src/pages/before-implement/privacy/cmp-privacy-and-general-data-protection-regulation.md

Steps to Reproduce: 
1. Go to https://developer-stage.adobe.com/target/before-implement/privacy/cmp-privacy-and-general-data-protection-regulation/#privacy-and-data-protection-regulations-faq
2. Click any of the side links that navigate you down the page
3. Hover to the right of the end of any title
4. Observe yellow highlighted "#" symbol

Expected Behavior: Checked other live pages and this is not visible

![Uploading Screen Shot 2022-05-25 at 1.34.27 PM.png…]()

**Comment by sgoffadobe** [comment]
Seems to be impacting most if not all pages (some don't have the hashtag highlighted yellow, but have the hashtag)

**Comment by judy-kim** [comment]
Hashtag appears (as expected) with cursor hover, indicating a section you can jump to. Hashtag will appear highlighted in yellow if, depending on your browser, it happens to be the keyword search -- is that maybe what happened here? (i.e. If you search the page for "#", any hashtag symbols will appear in yellow highlight on the page (depending on the browser).)

Closing with the assumption that this is what happened here, as this is the only way I could reproduce the issue. Please reopen if you find this issue persists!
