### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mmaxen** [AdobeDocs/target-developers#39]
Issue in /src/pages/implement/client-side/atjs/on-device-decisioning/on-device-decisioning.md

Broken links as pointed out in the screenshot: 
![image](https://user-images.githubusercontent.com/106278998/170362896-fec5c8c7-d7ef-4fdf-8819-bdc7debf7f0d.png)

**Comment by judy-kim** [comment]
Fixed as a result of addressing Issue #78.
