### ISSUE TITLE
Server-side Rendering (SSR) Demo App link context missing

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target-developers#46]
Issue in /src/pages/implement/server-side/sdk-guides/sample-apps/index.md

Link text: [Server-side Rendering (SSR) Demo App](https://github.com/adobe/target-nodejs-sdk-samples/tree/master/next-server-side-rendering-demo) And destination page and link do seem to "match"

**Comment by judy-kim** [comment]
This seems to be the correct destination link -- [Server-side Rendering (SSR) Demo App](https://github.com/adobe/target-nodejs-sdk-samples/tree/master/next-server-side-rendering-demo) -- an SSR Demo App in the Target Node.js SDK Samples repo.
