### ISSUE TITLE
Link goes to corp.adobe.com

### ISSUE THREAD

**Issue by mtalbot29** [AdobeDocs/target-developers#48]
Issue in /src/pages/implement/mobile/prefetch-offer-content.md

Prefetch functionality is not supported for Auto-Allocate and Auto-Target traffic allocation methods, for Automated Personalization or Recommendations activity types, or for [recommendations offers within an A/B or XT activity](https://experienceleague.corp.adobe.com/docs/target/using/recommendations/recommendations-as-an-offer.html).

**Comment by judy-kim** [comment]
Dupe of Issue #78. Fixed.
