### ISSUE TITLE
2017 Privacy Tech Vendor Report link requires two clicks to download

### ISSUE THREAD

**Issue by sgoffadobe** [AdobeDocs/target-developers#50]
Issue in /src/pages/before-implement/privacy/cmp-privacy-and-general-data-protection-regulation.md

Steps to Reproduce: 
1. Go to URL https://developer-stage.adobe.com/target/before-implement/privacy/cmp-privacy-and-general-data-protection-regulation/#what-response-does-target-send-to-the-gdpr-api-for-an-access-request
2. Click the link for [2017 Privacy Tech Vendor Report] (https://iapp.org/media/pdf/resource_center/Tech-Vendor-Directory-1.4.1-electronic.pdf) 
3. Observe that the download will only be triggered if clicked twice

**Comment by sgoffadobe** [comment]
Same thing occurs for [The Adobe Privacy JavaScript Library and GDPR](https://experienceleague.adobe.com/docs/experience-platform/privacy/home.html?lang=en)

**Comment by judy-kim** [comment]
Could not reproduce -- able to load destination links (both the "2017 Privacy Tech Vendor Report," as well as the "Adobe Privacy JavaScript Library and GDPR" page) with a single click for each, as expected. Subsequent download of the 2017 Report takes a separate click, as expected.
