### ISSUE TITLE
The Github Repo Link can be pointed to Sample Apps or SDK repos

### ISSUE THREAD

**Issue by bennet-roy** [AdobeDocs/target-developers#54]
On page - https://github.com/AdobeDocs/target-developers, the first link on the right hand panel under Resources titled "Adobe Target GitHub Repo" is currently pointing to the documentation repo, I think it makes sense to point it to our Adobe Target open source Git repo(s) where we have Sample apps or SDK source(s).

**Comment by judy-kim** [comment]
Additional notes from Bennet:

I meant this repo - https://github.com/adobe

But this one has everything from Adobe , not just Adobe Target related stuff. So, I wonder if we should create a new page with a curated list of repos first and then link it.

For example:

Node JS SDK Source - https://github.com/adobe/target-nodejs-sdk
Node JS SDK Examples Repo - https://github.com/adobe/target-nodejs-sdk-samples
Java SDK Source - https://github.com/adobe/target-java-sdk
Java SDK Example Repo - https://github.com/adobe/target-java-sdk-samples

**Comment by judy-kim** [comment]
Did not create a new page, but did link the suggested list of repos (above) under the Resources section on the page.

If a single, consolidated page is needed in the future, can do so as an enhancement.
