### ISSUE TITLE
Links don't work and are pointing outside of portal

### ISSUE THREAD

**Issue by hartungAdobe** [AdobeDocs/target-developers#57]
Issue in /src/pages/implement/client-side/atjs/atjs-functions/adobe-target-trackevent.md

These event-tracking mbox calls can then be used to define metrics in activities. For more information, see [Success Metrics](https://experienceleague.corp.adobe.com/docs/target/using/activities/success-metrics/success-metrics.html) and [Track Conversions](https://experienceleague.corp.adobe.com/docs/target/using/implement-target/client-side/at-js-implementation/deploy-at-js/implementing-target-without-a-tag-manager.html#task_E85D2F64FEB84201A594F2288FABF053).

Success Metrics and Track Conversions links don't work.

**Comment by judy-kim** [comment]
Root cause same as Issue #78. Fixed.
