### ISSUE TITLE
Link for "How Adobe Target Works" references adobe corp page

### ISSUE THREAD

**Issue by sgoffadobe** [AdobeDocs/target-developers#63]
Issue in /src/pages/before-implement/privacy/cookie-behavior.md

Steps to Reproduce: 
1. Go to https://developer-stage.adobe.com/target/before-implement/privacy/cookie-behavior/
2. Click [How Adobe Target Works](https://experienceleague.corp.adobe.com/docs/target/using/introduction/how-target-works.html)
3. Observe that internal page is referenced

**Comment by sgoffadobe** [comment]
Also impacted is the link for [profile lifetime length](https://experienceleague.corp.adobe.com/docs/target/using/audiences/visitor-profiles/visitor-profile-lifetime.html)

**Comment by judy-kim** [comment]
Dupe of Issue #78
