### ISSUE TITLE
Wrong URL for hyperlink "Sending data to Google Analytics via Platform Web SDK"

### ISSUE THREAD

**Issue by r-solis** [AdobeDocs/target-developers#66]
Issue in /src/pages/implement/client-side/aep-web-sdk.md

[Sending data to Google Analytics via Platform Web SDK](https://experienceleague.corp.adobe.com/docs/target/using/administer/response-tokens.html#platform-web-sdk) should link to https://experienceleague.corp.adobe.com/docs/target/using/administer/response-tokens.html#sending-data-to-google-analytics-via-platform-web-sdk

**Comment by judy-kim** [comment]
Fixed
