### ISSUE TITLE
3.2 Missing content/incorrect link on Deliver API linked page for "Delivery API"

### ISSUE THREAD

**Issue by saucier-adobe** [AdobeDocs/target-developers#69]
How impressions are triggered[#](https://developer-stage.adobe.com/target/implement/server-side/sdk-guides/core-principles/event-tracking/#how-impressions-are-triggered)
Target SDKs call the underlying [Delivery API](https://developer-stage.adobe.com/target/implement/server-side/sdk-guides/implement/delivery-api/). When an execute object with required parameters is within the request itself, the impression is incremented automatically for qualifying activities. SDK methods that increment an impression automatically are:

getOffers()
getAttributes()

^^Above link for Delivery API goes to blank page.^^
https://developer-stage.adobe.com/target/implement/server-side/sdk-guides/implement/delivery-api/

**Comment by judy-kim** [comment]
Issue in /src/pages/implement/server-side/sdk-guides/core-principles/event-tracking.md

**Comment by judy-kim** [comment]
Fixed
