### ISSUE TITLE
Awkward redundancy of links/nav

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target-developers#71]
Issue in /src/pages/implement/server-side/node-js/index.md

Bottom of page includes a list of pages in the section (also in the the left name). Possibly instead of calling it "next steps" maybe "related topics" would work better.

![image](https://user-images.githubusercontent.com/15110344/170365814-9229b7f4-0083-42ba-90d9-6478ac028732.png)

**Comment by judy-kim** [comment]
Asking IO team where/how to change this Next Steps header

**Comment by judy-kim** [comment]
IO team confirmed "that's something that you can't change unfortunately."
