### ISSUE TITLE
links outside of Adobe domain are not flagged and do not warn that you are navigating away from adobe.com or that it's an external link. example link : https://www.java.com/en/configure_crypto.html 

### ISSUE THREAD

**Issue by vishalwani** [AdobeDocs/target-developers#74]
Issue in /src/pages/before-implement/tls-transport-layer-security-encryption.md

**Comment by vishalwani** [comment]
similar example. : For more information about ITP, see [Apple Intelligent Tracking Prevention (ITP) 2.x](https://developer-stage.adobe.com/target/before-implement/privacy/apple-itp-2x/). under "CNAME and Adobe Target" section.

**Comment by judy-kim** [comment]
While it is true there is no text or flag, any links that lead to pages outside of the developer doc portal (developer.adobe.com) open in a new tab, to help the user understand they have left the context of the current page (which remains preserved in the original tab). This includes links to experienceleague.adobe.com, as well as links external to Adobe entirely. Only links that stay within the dev doc portal open in the current tab.

That being said, there is another (separate) issue with the second example you listed: "For more information about ITP, see [Apple Intelligent Tracking Prevention (ITP) 2.x](https://developer-stage.adobe.com/target/before-implement/privacy/apple-itp-2x/). under "CNAME and Adobe Target" section." -- This link goes to another page within the dev doc portal, meaning it reloads in the current page as described above; however, the side nav fails to expand to indicate where in the site the user has been taken to. This loss of context is very confusing. I will open a new issue for this, but will close the current issue, as we will be using the context of current v. new tabs to indicate to users when they are being taken outside the dev portal.
