### ISSUE TITLE
3.2 Integration > AAM Segments footer link to "Introduction to On-Device Decisioning" has "/atjs" in destination link

### ISSUE THREAD

**Issue by saucier-adobe** [AdobeDocs/target-developers#75]
https://developer-stage.adobe.com/target/implement/server-side/sdk-guides/integration-with-experience-cloud/aam-segments/

Bottom nav "NEXT" link incorrect.

Similar to other submission, links to "Intro to On-Device Decisioning" seems to have extra folder "/atjs" within url. Remove and the page resolves:
FROM: https://developer-stage.adobe.com/target/implement/server-side/sdk-guides/`atjs/`on-device-decisioning/
TO: https://developer-stage.adobe.com/target/implement/server-side/sdk-guides/on-device-decisioning/

**Comment by judy-kim** [comment]
Fixed when [this issue](https://github.com/AdobeDocs/target-developers/issues/21) was fixed (same root cause).
