### ISSUE TITLE
Link suggestion

### ISSUE THREAD

**Issue by mmaxen** [AdobeDocs/target-developers#77]
Issue in /src/pages/implement/client-side/atjs/target-atjs-faq/target-atjs-faq.md

This link possibly should go to this URL instead:  https://developer-stage.adobe.com/target/implement/client-side/atjs/how-to-deployatjs/implement-target-without-a-tag-manager/#download-atjs-using-the-target-interface 

![image](https://user-images.githubusercontent.com/106278998/170366836-a474a135-f888-4996-8870-f4d69faf9155.png)

**Comment by judy-kim** [comment]
Updated text and links for clarity. Thanks!
