### ISSUE TITLE
3.2 Transition from Target legacy APIs to Adobe I/O > Equivalent Methods terminology for methods

### ISSUE THREAD

**Issue by saucier-adobe** [AdobeDocs/target-developers#79]
Clarification needed for column headings, i.e. "Legacy API Method" vs "New API Method" should be more accurately descriptive, i.e. 
Legacy Test & Target vs Adobe I/O (or other), as the "New" ones link to docs that have been around for some time. May be confusing.

![image](https://user-images.githubusercontent.com/15110214/170367942-e59cda71-aa0a-4dae-a92d-ea19d9276ac8.png)

**Comment by judy-kim** [comment]
Issue refers to src/pages/implement/server-side/transition-from-target-legacy-apis.md

**Comment by judy-kim** [comment]
Changed "Legacy API" to "Classic API" (shorter than "Legacy Test & Target"). Changed "new API" to "Adobe I/O API."

Open to suggestions for different replacement terms, but closing for now.

**Comment by judy-kim** [comment]
Need to updates references to "Adobe I/O" to either "Adobe Developer Console" (product) or "Adobe Developer Platform" (overall platform). In most cases, better to use product name.
