### ISSUE TITLE
Language not clear and Link Suggestion

### ISSUE THREAD

**Issue by mmaxen** [AdobeDocs/target-developers#83]
Issue in /src/pages/implement/client-side/atjs/upgrading-from-atjs-1x-to-atjs-20.md

The language highlighted in this screenshot is not super clear.  I'm assuming it meant to say This setting is supported in v 2.1.0 and greater.

Also the link for version 2.1.0 should go straight to: https://developer-stage.adobe.com/target/implement/client-side/atjs/target-atjs-versions/#atjs-version-210-june-3-2019  

![image](https://user-images.githubusercontent.com/106278998/170368678-e6e85146-3e94-4112-bd73-c41c7b772f30.png)

**Comment by judy-kim** [comment]
Thanks for the great suggestions. Much clearer. Fixed!
