### ISSUE TITLE
Possibly incorrect link to old docs

### ISSUE THREAD

**Issue by mmaxen** [AdobeDocs/target-developers#87]
Issue in /src/pages/implement/client-side/atjs/upgrading-from-atjs-1x-to-atjs-20.md

<img width="604" alt="image" src="https://user-images.githubusercontent.com/106278998/171237271-dec5731d-9089-440b-a6eb-882974bb5b2f.png">

the link in the screenshot goes to: https://experienceleague.adobe.com/docs/target-learn/tutorials/implementation/understanding-how-atjs-20-works.html which appears to be the older docs

**Comment by judy-kim** [comment]
Link goes to the intended page -- the destination is a Target "tutorial" page on Experience League. (The tutorials are similar in layout to, but different from, the [standard Target documentation](https://experienceleague.adobe.com/docs/target/using/target-home.html?lang=en).)
