### ISSUE TITLE
Outdated Screenshot

### ISSUE THREAD

**Issue by mmaxen** [AdobeDocs/target-developers#88]
Issue in /src/pages/implement/client-side/atjs/global-mbox/customize-global-mbox.md

<img width="987" alt="image" src="https://user-images.githubusercontent.com/106278998/171244772-e24da1bd-7ee7-436d-8a05-2ce766cd6d1a.png">

**Comment by mtalbotgmail** [comment]
Image has been updated: https://developer.adobe.com/target/implement/client-side/atjs/global-mbox/customize-global-mbox/
