### ISSUE TITLE
Tutorial badge looks wonky

### ISSUE THREAD

**Issue by mtalbot29** [AdobeDocs/target-developers#91]
Issue in /src/pages/implement/client-side/atjs/atjs-functions/atjs-custom-events.md

Jon wanted these, but I have never liked them. The distinction between the different types is minuscule.

**Comment by judy-kim** [comment]
Issue applies to other badges as well - Platform, Premium, and Overview.

May remove the badges instead of fighting the formatting in order to get them to align the way they do on ExL.

**Comment by mtalbotgmail** [comment]
Not an issue in new site.
