### ISSUE TITLE
Code boxes - redundant labeling

### ISSUE THREAD

**Issue by judy-kim** [AdobeDocs/target-developers#97]
Issue in /src/pages/implement/server-side/sdk-guides/getting-started/index.md

Code boxes throughout repo - redundant labeling of language (e.g. Java, .NET, Python, Node.js)

Within the code box, the language (e.g. Java, .NET, Python, Node.js) appears in both the tab headers on the left, as well as the dropdown on the right - should remove one for a cleaner experience.

![temp](https://user-images.githubusercontent.com/57675076/174651819-c87c0a1e-9fff-4761-b782-0dd7a2e22cbd.png)

**Comment by judy-kim** [comment]
Figured out this is a bug for the IO team to handle. Logged [DEVSITE-448](https://jira.corp.adobe.com/browse/DEVSITE-448).

At present time, cannot choose either the tabs or the dropdown -- must have both present, even though it'll be redundant. (Theoretically, you should be able to not have the dropdown.)

**Comment by mtalbotgmail** [comment]
Not an issue in new guide.
